### PR TITLE
BREAKING CHANGE: Update Script contracts to take `get_bearer_token` function argument instead of static `bearer_token`

### PR DESCRIPTION
**Pull request by marijnvanderhorst**
sem-ver: api-break

## Proposed changes
Update all script contracts such that they take a `get_bearer_token` function as input to their `execute` functions, instead of a static `bearer_token` input. This allows scripts to run longer than the lifetime of a single access token, while still being able to make API requests to PriceCypher Engine.

## Types of changes

What types of changes does your code introduce to this repository?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Testing
Explain here how to run your unit tests, and explain how to execute manual testing. 

### Unit testing
n/a

### Manual testing
Let's test in DEV environment, together with updated Argo Runtime. See marketredesign/pc_generic_datascience_scripts#44.

## Further comments
Breaking change, so requires new major version to be released

### CODE REVIEW

**Review by EmielSchmeink — COMMENTED** [review]
LGTM, small question though (not very familiar with this repo) are there no tests?

**Comment by marijnvanderhorst** [comment]
> LGTM, small question though (not very familiar with this repo) are there no tests?

Not currently (only on the REST client included in this repo). Feel free to add tests though 😉

**Comment by EmielSchmeink** [comment]
> > LGTM, small question though (not very familiar with this repo) are there no tests?
> 
> Not currently (only on the REST client included in this repo). Feel free to add tests though 😉

I probably will then.

**Review by EmielSchmeink — APPROVED** [review]

**Comment by marijnvanderhorst** [comment]
> > > LGTM, small question though (not very familiar with this repo) are there no tests?
> > 
> > 
> > Not currently (only on the REST client included in this repo). Feel free to add tests though 😉
> 
> I probably will then.

I'll add a user story to the board for this. Let's include in a sprint when it makes sense 👍 

EDIT: [here](https://dev.azure.com/dttnl-consulting-PriceCypher/PriceCypher/_workitems/edit/101)

**Pull request merged**
